### PR TITLE
115 adding authorization to invitation endpoints and amend tests

### PR DESCRIPTION
**Pull request by PixieStick314**
## Description
(A short description of the changes you have made.)

## Related issues
(You can refer to it by #SomeID)

## Checklist
- [X] My code is in the right place.\
- [X] My code fully addresses the issue I was working on.\
- [X] I have added appropriate tests and error handling.\
- [X] My code follows the style guidelines.\
- [X] I have added relevant comments explaining the purpose and function of my code (if necessary).\
- [] I have added relevant documentation to the GitHub wiki.\
- [X] I have created a pull request and notified the teams.

### CODE REVIEW

**Review by DanielRBech — DISMISSED** [review]
Wouldnt the invitation endpoints also need to get the org id parsed with it?

**Comment by PixieStick314** [comment]
> Wouldnt the invitation endpoints also need to get the org id parsed with it?

That's not how claims are handled, so no. Also, the invitations already pass with an organization ID, as per main. All the tests pass, and I've run through this about 40 times, hence all the console.writeline lines.
You can just comment without requesting changes when there are parts you don't understand.

**Comment by LokeSGJ** [comment]
No, Daniel is right, the POST endpoint for invitations does need to have the orgId added to the header, otherwise it won't work with the OrganizationMember policy, as that policy only knows which organization you're trying to add by reading it from the route value. We're unfortunately not catching these types of bugs right now due to how our auth works in testing. I was surprised too, but it's true.

**Comment by PixieStick314** [comment]
> No, Daniel is right, the POST endpoint for invitations does need to have the orgId added to the header, otherwise it won't work with the OrganizationMember policy, as that policy only knows which organization you're trying to access by reading it from the route value. We're unfortunately not catching these types of bugs right now due to how our auth works in testing. I was surprised too, but it's true.

That's really bad and an issue with the policy; it has nothing to do with the changed files. In fact, reading the OrgMember policy makes me question why you approved it in the first place. Regardless, it has nothing to do with this pull request and instead should be made into an issue to change the policy, as otherwise every other endpoint that uses it has to be changed as well

**Pull request closed without merging**
