### PR TITLE
Added Swagger documentation to the endpoints.

### PR DESCRIPTION
**Pull request by PixieStick314**
# Description

*Added Swagger Documentation to each endpoint*

Fixes #\13

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [x ] This change is a documentation update

# How Has This Been Tested?

*It has not*

# Checklist:

- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [X ] My changes generate no new warnings

### CODE REVIEW

**Review by LokeSGJ — CHANGES_REQUESTED** [review]
When I try to launch this branch I get 55 errors in UserEndpoints

**Review by NSpahic22 — DISMISSED** [review]
Looks good. :)

**Review by NSpahic22 — APPROVED** [review]
Still looks good :)

**Review by DanielRBech — APPROVED** [review]
LGTM :D

**Review by Tbjerregaard — APPROVED** [review]
Swagger messages seems detailed enough overall LGTM

**Review by LokeSGJ — APPROVED** [review]

**Pull request merged**
